### ISSUE TITLE
Preview doesn't tile correctly

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#125]
![image](https://user-images.githubusercontent.com/68207888/143607415-d328c5aa-5ad9-45c7-990e-b6a6a6dde156.png)

**Comment by definitely-nobody-is-here** [comment]
This has been fixed already, stop posting stuff I already told you was fixed

**Comment by maitian352** [comment]
![image](https://user-images.githubusercontent.com/68207888/147712818-dca374f5-8efe-4929-837b-7243227d623d.png)
LOL not fixed
